### PR TITLE
Update @tag definitions

### PR DESCRIPTION
**Pull request by trevor-scheer**

### CODE REVIEW

**Review by EverlastingBugstopper — APPROVED** [review]
cc @prasek these are the changes to make composition succeed

**Comment by EverlastingBugstopper** [comment]
lets hold off merging this until we are ready to release rover (likely tomorrow), then we can have a smaller window where CI is failing due to old builds of rover

**Comment by prasek** [comment]
@trevor-scheer if https://github.com/apollographql/federation/pull/1022 will allow the existing `@tag` directive declarations to work then perhaps we can cut a new harmonizer with that and use that for the new `rover` drop? /cc @EverlastingBugstopper @abernix

**Comment by EverlastingBugstopper** [comment]
This PR can be closed

**Pull request closed without merging**
