### PR TITLE
Add serverless example

### PR DESCRIPTION
**Pull request by gabsn**
As seen in #150 , this PR is an attempt to showcase how subgraphs can be composed at build time in a serverless context.

@prasek can you give a look at it?

Basically you can run `yarn dev` in the `serverless` folder (make sure to have installed all the dependencies). And then you will have a serverless env running on your localhost:

image

Then if you go to [localhost:3000/router](http://localhost:3000/router), you should be able to query the federated router from the playground:

image

At this point there seems to be an error due to unexpected json response body, but the architecture is here. I will look it onto fix this issue later.

Can you tell me if the overall architecture and code organization look ok for you? 
Do you want me to update the README and add make endpoints for the serverless example also?

PS: I've pushed the `yarn.lock` because this is a best practice when working in node projects, but maybe you have your own reasons to leave it aside?

### CODE REVIEW

**Comment by prasek** [comment]
@gabsn awesome will take a look later today 🚀

**Comment by prasek** [comment]
@gabsn took a look and got it running locally, general approach/layout looks great 👍 

had a few goals in mind for the supergraph-demo:
1. keep it as simple as possible - same level of details as the federation docs - for example: [create a gateway](https://www.apollographql.com/docs/federation/quickstart/#2-create-a-gateway)
   * minimize # of files, don't include .lock files, minimize folder nesting, just show how simple the code is
2. embrace the whole Apollo Federation community, esp. those not coming from a Node background
   * Dockerize everything - so you don't have to have npm, node install on your dev laptop to run the demo
   * Have a make command for doing the demo

If you want to get your PR ready to land, I'm happy to help adapt it along these lines after it lands -- or if you want to do that as part of the PR that works too! 🙏

**Comment by gabsn** [comment]
@prasek since I don't know exactly how you'd like it to be, it'd be nice you take it from there. Otherwise, I'm afraid we're wasting time going back and forth.

**Comment by prasek** [comment]
@gabsn here are some finishing touches, lmk if you'd like any changes before merging and thanks for the contribution! 🎉

**Pull request merged**
